### ISSUE TITLE
TinyMCE editor not active in list element

### ISSUE THREAD

**Issue by superDuperCyberTechno** [newbthenewbd/grav-plugin-tinymce-editor#14]
So, if you add editors dynamically via a list, the Markdown editor isn't replaced by the TinyMCE editor.

From the page blueprint:

```
            header.contentlist:
              type: list
              btnLabel: Add content block
              controls: both
              style: vertical
              fields:
                .title:
                  type: text
                  label: Title
                .content:
                  type: editor
```
