### ISSUE TITLE
Select default font family 

### ISSUE THREAD

**Issue by nguyenchihien** [newbthenewbd/grav-plugin-tinymce-editor#16]
Hi!
The font selector is a interesting function. It helps me alot in my posts. 
But I wanna change "default font" into "Tahoma", currently it's "Verdana"
If can, also change the others default parameter : font size, color , bold/ italic .......
Thank you!

**Comment by newbthenewbd** [comment]
You could append a `content_style` parameter under `parameters` in `tinymce-editor.yaml`, like this:
```
parameters:
  -
    name: fontsize_formats
    value: '6pt 7pt 8pt 9pt 10pt 11pt 12pt 13pt 14pt 15pt 16pt 18pt 20pt 22pt 24pt 26pt 28pt 32pt 36pt 40pt 44pt 48pt 54pt 60pt 66pt 72pt 80pt 88pt 96pt'
  -
    name: paste_data_images
    value: '1'
  -
    name: content_style
    value: '.mce-content-body{font:48pt Tahoma, sans-serif}'
```
This enables You to modify the CSS styles used by TinyMCE. To actually default to a font in a theme, though, You'll have to modify the theme's CSS - likewise, the default Verdana font isn't actually used by the pages until manually set using the selector.
