### ISSUE TITLE
Keeps changing my urls

### ISSUE THREAD

**Issue by nconroy** [newbthenewbd/grav-plugin-tinymce-editor#22]
I have a folder with subpages and cant get the links working. 

Tried using the absolute URL "/folder/page" the url is converted to ../page
Tried using the relative path from the folder "page" but it also gets converted to ../page
I have added relative_urls=false to the config but it has had no effect

**Comment by newbthenewbd** [comment]
Have You set the `relative_urls` parameter under `parameters`? This is roughly how it should look in `tinymce-editor.yaml` to get properly interpreted:
```
parameters:
  -
    name: fontsize_formats
    value: '6pt 7pt 8pt 9pt 10pt 11pt 12pt 13pt 14pt 15pt 16pt 18pt 20pt 22pt 24pt 26pt 28pt 32pt 36pt 40pt 44pt 48pt 54pt 60pt 66pt 72pt 80pt 88pt 96pt'
  -
    name: paste_data_images
    value: '1'
  -
    name: relative_urls
    value: '0'
```
