### ISSUE TITLE
Browser SpellCheck  disabled with tinymce plugin

### ISSUE THREAD

**Issue by dryland404** [newbthenewbd/grav-plugin-tinymce-editor#28]
Something's not set up right for Chrome
Browser spell check is not enabled with tinymce

**Comment by newbthenewbd** [comment]
To enable the built-in browser spellcheck for TinyMCE, You may set `browser_spellcheck` to true under `parameters` in `/user/config/plugins/tinymce-editor.yaml`, like this:
```
parameters:
  -
    name: fontsize_formats
    value: '6pt 7pt 8pt 9pt 10pt 11pt 12pt 13pt 14pt 15pt 16pt 18pt 20pt 22pt 24pt 26pt 28pt 32pt 36pt 40pt 44pt 48pt 54pt 60pt 66pt 72pt 80pt 88pt 96pt'
  -
    name: paste_data_images
    value: '1'
  -
    name: browser_spellcheck
    value: '1'
```
