### ISSUE TITLE
Language URL not loading

### ISSUE THREAD

**Issue by pieter91** [newbthenewbd/grav-plugin-tinymce-editor#38]
I have my user account  language set to something other than english. But the TinyMCE javascript doesn't refer to the correct language file in the language_url field. The value becomes "/" on the source of the edit page. 

I'm not familiar enough with twig and grav to understand what's happening exactly. But wouldn't it be easier to set the language in the "language" field?

**Comment by newbthenewbd** [comment]
I don't think so, sadly, as, if I recall correctly, TinyMCE follows a language code standard that is different from the one Grav uses. The correct language is therefore guessed; the last time I checked, the system seemed to work pretty well, but I haven't tested all of the languages. I will try looking into it ASAP, although cannot promise anything, as for the few weeks to come my free time unfortunately stays scarce. Could You specify what language exactly it is?

Thanks for reporting!

**Comment by pieter91** [comment]
I'm trying to load "nl". 

As I said, I don't know enough about grav, but would it be possible to add a dropdown menu to the user account settings page in the admin interface? Or is that not allowed? 

A good solution in my case would be to set a site-wide language for TinyMCE, circumventing the user's chosen language. But I can imagine that won't suit everyone.

**Comment by newbthenewbd** [comment]
From what I've acquired, this seems to be caused by a regression in the recent versions of Grav, specifically, the `url()` Twig function not working as it used to, and as documentation suggests it should. As of the time of this writing, the problem [could have even been observed](http://web.archive.org/web/20190524150521/https://learn.getgrav.org/16/themes/twig-filters-functions) in the official Grav Documentation.

A workaround that I suggest until this change is confirmed to be deliberate, thus mandating the plugin's update, or a mistake, thus requiring changes to Grav, is to specify the language URL in the plugin's config, like this:
```
parameters:
  -
    name: fontsize_formats
    value: '6pt 7pt 8pt 9pt 10pt 11pt 12pt 13pt 14pt 15pt 16pt 18pt 20pt 22pt 24pt 26pt 28pt 32pt 36pt 40pt 44pt 48pt 54pt 60pt 66pt 72pt 80pt 88pt 96pt'
  -
    name: paste_data_images
    value: '1'
  -
    name: language_url
    value: '/site/user/plugins/tinymce-editor/js/tinymce/langs/nl.js'
```
