### ISSUE TITLE
Error: Required jwt token provider not defined. (0)

### ISSUE THREAD

**Issue by josecarvalhoSigned** [newbthenewbd/grav-plugin-tinymce-editor#48]
Hi, when i upload an image i get this error. 

![image](https://user-images.githubusercontent.com/44067633/85855053-7fd34980-b7ad-11ea-9cb5-e2218362ad41.png)

I know it has something to do with JWT authentication to ensure the security of my images, and from what I read I have to insert a token generated in my Tiny Cloud account somewhere, I just don't know where. Can you help me?

**Comment by newbthenewbd** [comment]
You can add the JWT token provider URL to the parameters in `user/config/plugins/tinymce-editor.yaml` (if it doesn't exist, copy the `tinymce-editor.yaml` from `user/plugins/tinymce-editor/tinymce-editor.yaml` there first), like this:
```
parameters:
  -
    name: fontsize_formats
    value: '6pt 7pt 8pt 9pt 10pt 11pt 12pt 13pt 14pt 15pt 16pt 18pt 20pt 22pt 24pt 26pt 28pt 32pt 36pt 40pt 44pt 48pt 54pt 60pt 66pt 72pt 80pt 88pt 96pt'
  -
    name: paste_data_images
    value: '1'
  -
    name: tinydrive_token_provider
    value: 'you-know-better-what-to-put-here'
```
