### ISSUE TITLE
Can't change pagebreak content

### ISSUE THREAD

**Issue by gmvoliveira** [newbthenewbd/grav-plugin-tinymce-editor#6]
How do I change the content that is used as pagebreak? Default value is `<!-- pagebreak -->` and can be edited in the pagebreak plugin file. Is this or will this be editable via tinymce-editor.yaml?

**Comment by newbthenewbd** [comment]
In `tinymce-editor.yaml`, under the `parameters` section, You can append Your own parameters to use with TinyMCE. According to [the documentation](https://www.tinymce.com/docs/plugins/pagebreak/#pagebreak_separator) the correct parameter to set is called `pagebreak_separator`.

This is how the parameters section with it added could look like:
```
parameters:
  -
    name: fontsize_formats
    value: '6pt 7pt 8pt 9pt 10pt 11pt 12pt 13pt 14pt 15pt 16pt 18pt 20pt 22pt 24pt 26pt 28pt 32pt 36pt 40pt 44pt 48pt 54pt 60pt 66pt 72pt 80pt 88pt 96pt'
  -
    name: paste_data_images
    value: '1'
  -
    name: pagebreak_separator
    value: '<!-- my page break -->'
```
